export const GET_EXPENSES = 'GET_EXPANSES';
export const EXPENSES_RECIEVED_SUCCESS = 'EXPENSES_RECIEVED_SUCCESS';
export const EXPENSES_REQUEST_FAILED = 'EXPENSES_REQUEST_FAILED';

export const UPDATE_EXPENSES = 'UPDATE_EXPANSES';
export const UPDATE_EXPENSES_SUCCESS = 'UPDATE_EXPANSES_SUCCESS';
export const UPDATE_EXPENSES_FAILED = 'UPDATE_EXPANSES_FAILED';

export const CREATE_EXPENSE = 'CREATE_EXPANSE';
export const EXPENSES_CREATED_SUCCESS = 'EXPENSES_CREATED_SUCCESS';
export const EXPENSES_CREATED_FAILED = 'EXPENSES_CREATED_FAILED';

